-- ============================================================================
--  Portal RvR Tecnologías · Esquema PostgreSQL
--  Fiel al diagrama vigente de dbdiagram.io (11 tablas), sin cambios de modelo.
--
--  Traducción de tipos desde la notación del diagrama:
--    int PK autoincremental  ->  int GENERATED BY DEFAULT AS IDENTITY
--    datetime                ->  timestamptz  (Medellín es UTC-5 y el portal
--                                 muestra tiempos relativos: "hace 9 h")
--    decimal(10,2)           ->  numeric(10,2)
--    varchar(n) / text       ->  igual
--
--  Los NOT NULL son exactamente los que el diagrama marca con NN. Los DEFAULT
--  de fecha se agregan por comodidad: no cambian la forma del modelo y evitan
--  que cada INSERT tenga que pasar la fecha a mano.
--
--  Ejecutar con:  psql "<cadena de conexión>" -f db/01-esquema.sql
-- ============================================================================

BEGIN;

DROP TABLE IF EXISTS abonos, ventas, diagnosticos, ordenes_servicio,
  agendamientos, servicios, categorias, usuarios, roles_permisos,
  permisos, roles CASCADE;

-- ---------------------------------------------------------------- seguridad

CREATE TABLE roles (
  id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      varchar(50) NOT NULL,
  descripcion varchar(255),
  estado      varchar(20)
);

CREATE TABLE permisos (
  id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      varchar(50) NOT NULL,
  modulo      varchar(20),
  descripcion varchar(255),
  estado      varchar(20)
);

-- Puente rol <-> permiso. Los permisos van precargados, sin CRUD en la app.
CREATE TABLE roles_permisos (
  rol_id     int REFERENCES roles (id),
  permiso_id int REFERENCES permisos (id),
  PRIMARY KEY (rol_id, permiso_id)
);

CREATE TABLE usuarios (
  id              int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rol_id          int REFERENCES roles (id),
  nombre_usuario  varchar(50) NOT NULL,
  correo          varchar(100) NOT NULL,
  contrasena_hash varchar(255) NOT NULL,
  nombres         varchar(100) NOT NULL,
  apellidos       varchar(100) NOT NULL,
  telefono        varchar(20),
  estado          varchar(20),
  fecha_creacion  timestamptz DEFAULT now()
);

-- ----------------------------------------------------------------- catálogo

CREATE TABLE categorias (
  id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      varchar(80) NOT NULL,
  descripcion varchar(255),
  estado      varchar(20)
);

CREATE TABLE servicios (
  id           int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  categoria_id int REFERENCES categorias (id),
  nombre       varchar(100) NOT NULL,
  descripcion  text,
  precio       numeric(10,2) NOT NULL,
  estado       varchar(20)
);

-- ----------------------------------------------------------------- operación

-- cliente_id y tecnico_id apuntan a usuarios: en este modelo ambos son
-- usuarios del sistema, distinguidos por su rol.
CREATE TABLE agendamientos (
  id               int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id       int REFERENCES usuarios (id),
  tecnico_id       int REFERENCES usuarios (id),
  servicio_id      int REFERENCES servicios (id),
  fecha_programada timestamptz NOT NULL,
  estado           varchar(20),
  notas            text,
  fecha_creacion   timestamptz DEFAULT now()
);

CREATE TABLE ordenes_servicio (
  id                   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agendamiento_id      int REFERENCES agendamientos (id),
  cliente_id           int REFERENCES usuarios (id),
  tecnico_id           int REFERENCES usuarios (id),
  servicio_id          int REFERENCES servicios (id),
  estado               varchar(30),
  descripcion_problema text,
  fecha_ingreso        timestamptz DEFAULT now(),
  fecha_entrega        timestamptz
);

CREATE TABLE diagnosticos (
  id                 int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_id           int REFERENCES ordenes_servicio (id),
  tecnico_id         int REFERENCES usuarios (id),
  hallazgos          text NOT NULL,
  solucion_propuesta text,
  fecha_diagnostico  timestamptz DEFAULT now()
);

-- --------------------------------------------------------------------- venta

CREATE TABLE ventas (
  id              int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_id        int REFERENCES ordenes_servicio (id),
  cliente_id      int REFERENCES usuarios (id),
  monto_total     numeric(10,2) NOT NULL,
  saldo_pendiente numeric(10,2) NOT NULL,
  estado_pago     varchar(30),
  fecha_venta     timestamptz DEFAULT now()
);

CREATE TABLE abonos (
  id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venta_id    int REFERENCES ventas (id),
  monto       numeric(10,2) NOT NULL,
  metodo_pago varchar(30) NOT NULL,
  referencia  varchar(100),
  fecha_abono timestamptz DEFAULT now()
);

-- ------------------------------------------------------------------ índices
-- Sobre las columnas por las que el portal filtra y ordena en cada listado.

CREATE INDEX ix_usuarios_rol            ON usuarios (rol_id);
CREATE INDEX ix_servicios_categoria     ON servicios (categoria_id);
CREATE INDEX ix_agenda_tecnico_fecha    ON agendamientos (tecnico_id, fecha_programada);
CREATE INDEX ix_agenda_cliente          ON agendamientos (cliente_id);
CREATE INDEX ix_ordenes_estado          ON ordenes_servicio (estado);
CREATE INDEX ix_ordenes_cliente         ON ordenes_servicio (cliente_id);
CREATE INDEX ix_ordenes_tecnico         ON ordenes_servicio (tecnico_id);
CREATE INDEX ix_ordenes_fecha_ingreso   ON ordenes_servicio (fecha_ingreso DESC);
CREATE INDEX ix_diagnosticos_orden      ON diagnosticos (orden_id);
CREATE INDEX ix_ventas_orden            ON ventas (orden_id);
CREATE INDEX ix_ventas_cliente          ON ventas (cliente_id);
CREATE INDEX ix_abonos_venta            ON abonos (venta_id);

COMMIT;
