-- ============================================================================
--  Portal RvR Tecnologías · Esquema PostgreSQL · Modelo corregido (15 tablas)
--
--  Parte del diagrama de 11 tablas y le aplica las correcciones de la revisión
--  del 18 de septiembre. El detalle de qué cambió y por qué está en
--  `db/README.md`; el modelo para dbdiagram.io, en `db/modelo.dbml`.
--
--  Tablas:   roles · permisos · roles_permisos · usuarios · clientes
--            tecnicos · categorias · servicios · metodos_pago
--            ordenes_servicio · orden_servicio_detalle · agendamientos
--            diagnosticos · ventas · abonos
--  Vista:    v_ventas  (abonado, saldo y estado de pago, siempre calculados)
--
--  ⚠ Empieza con DROP: borra la base anterior (la de 11, la de 13 o esta).
--  Solo se corre sobre una base sin datos reales.
--
--  Ejecutar con:  psql -U postgres -d rvr -f db/01-esquema.sql
-- ============================================================================

BEGIN;

-- ------------------------------------------------------------ limpieza
-- Nombres del modelo anterior y del actual: sirve para migrar desde el de 11
-- tablas y para volver a crear este desde cero.

DROP VIEW  IF EXISTS v_ventas;
DROP TABLE IF EXISTS abonos, ventas, diagnosticos, agendamientos,
  orden_servicio_detalle, ordenes_servicio, metodos_pago, servicios,
  categorias, tecnicos, clientes, usuarios, roles_permisos, permisos,
  roles CASCADE;
DROP FUNCTION IF EXISTS exigir_rol() CASCADE;
DROP FUNCTION IF EXISTS validar_abono() CASCADE;
DROP TYPE IF EXISTS estado_registro, estado_usuario, estado_servicio,
  estado_orden, estado_agenda, estado_venta, tipo_pago, estado_abono,
  estado_tecnico, tipo_documento CASCADE;

-- ------------------------------------------------------------ listas cerradas
-- Antes eran varchar sin validar: "completada", "Completada" y "completda"
-- entraban como tres estados distintos. Ahora la base rechaza lo que no esté
-- en la lista. Los valores son los mismos que ya usa el portal.

CREATE TYPE estado_registro AS ENUM ('activo', 'inactivo');

CREATE TYPE estado_usuario  AS ENUM ('activo', 'invitacion_enviada',
                                     'inactivo', 'bloqueado');

CREATE TYPE estado_servicio AS ENUM ('activo', 'borrador', 'archivado');

CREATE TYPE estado_tecnico  AS ENUM ('disponible', 'en_ruta', 'en_sitio',
                                     'fuera_turno');

CREATE TYPE tipo_documento  AS ENUM ('CC', 'NIT', 'CE', 'PAS');

-- El orden de la lista es el orden del flujo: sirve para ORDER BY estado.
CREATE TYPE estado_orden    AS ENUM ('nueva', 'pendiente', 'aprobada',
                                     'programada', 'reprogramada',
                                     'en_proceso', 'completada', 'cancelada');

CREATE TYPE estado_agenda   AS ENUM ('programado', 'reprogramado',
                                     'en_curso', 'completado', 'cancelado');

CREATE TYPE estado_venta    AS ENUM ('vigente', 'anulada');

CREATE TYPE tipo_pago       AS ENUM ('anticipo', 'saldo');

CREATE TYPE estado_abono    AS ENUM ('por_conciliar', 'conciliado',
                                     'reembolsado');

-- ================================================================ seguridad

CREATE TABLE roles (
  id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      varchar(50)     NOT NULL UNIQUE,
  descripcion varchar(255),
  estado      estado_registro NOT NULL DEFAULT 'activo'
);

-- Precargados en la base, sin CRUD en la aplicación.
CREATE TABLE permisos (
  id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      varchar(50)     NOT NULL UNIQUE,
  modulo      varchar(20)     NOT NULL,
  descripcion varchar(255),
  estado      estado_registro NOT NULL DEFAULT 'activo'
);

CREATE TABLE roles_permisos (
  rol_id     int NOT NULL REFERENCES roles (id)    ON DELETE CASCADE,
  permiso_id int NOT NULL REFERENCES permisos (id) ON DELETE CASCADE,
  PRIMARY KEY (rol_id, permiso_id)
);

-- Las cuentas del portal. Una persona tiene tabla propia (clientes, tecnicos)
-- cuando tiene datos propios o puede existir sin cuenta; si solo se distingue
-- por lo que puede hacer, es un rol. Por eso el administrador no tiene tabla.
CREATE TABLE usuarios (
  id              int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rol_id          int            NOT NULL REFERENCES roles (id),
  nombre_usuario  varchar(50)    NOT NULL UNIQUE,
  correo          varchar(100)   NOT NULL,
  contrasena_hash varchar(255)   NOT NULL,
  nombres         varchar(100)   NOT NULL,
  apellidos       varchar(100)   NOT NULL,
  telefono        varchar(20),
  estado          estado_usuario NOT NULL DEFAULT 'activo',
  ultimo_acceso   timestamptz,
  fecha_creacion  timestamptz    NOT NULL DEFAULT now(),
  CONSTRAINT ck_usuarios_correo CHECK (correo ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$')
);

-- El login busca por correo: único sin importar mayúsculas.
CREATE UNIQUE INDEX ux_usuarios_correo ON usuarios (lower(correo));

-- ================================================================ personas

-- El cliente NO necesita cuenta: el que escribe por WhatsApp o llama se
-- registra igual. `usuario_id` solo se llena si además entra al portal.
CREATE TABLE clientes (
  id               int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id       int             UNIQUE REFERENCES usuarios (id),
  tipo_documento   tipo_documento  NOT NULL,
  numero_documento varchar(20)     NOT NULL,
  nombre           varchar(150)    NOT NULL,
  correo           varchar(100),
  telefono         varchar(20),
  direccion        varchar(200),
  ciudad           varchar(80),
  sector           varchar(80),
  estado           estado_registro NOT NULL DEFAULT 'activo',
  fecha_creacion   timestamptz     NOT NULL DEFAULT now(),
  UNIQUE (tipo_documento, numero_documento)
);

-- El técnico SÍ entra al portal (ve sus órdenes y registra diagnósticos), así
-- que siempre tiene cuenta. Nombre, correo y teléfono salen de `usuarios`.
CREATE TABLE tecnicos (
  id           int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id   int            NOT NULL UNIQUE REFERENCES usuarios (id),
  especialidad varchar(100)   NOT NULL,
  zona         varchar(80),
  estado       estado_tecnico NOT NULL DEFAULT 'disponible'
);

-- ================================================================= catálogo

CREATE TABLE categorias (
  id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      varchar(80)     NOT NULL UNIQUE,
  descripcion varchar(255),
  estado      estado_registro NOT NULL DEFAULT 'activo'
);

CREATE TABLE servicios (
  id            int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  categoria_id  int             NOT NULL REFERENCES categorias (id),
  nombre        varchar(100)    NOT NULL UNIQUE,
  descripcion   text,
  precio        numeric(10,2)   NOT NULL CHECK (precio >= 0),
  -- La ficha pide una garantía que varía según el servicio prestado.
  dias_garantia int             NOT NULL DEFAULT 0 CHECK (dias_garantia >= 0),
  estado        estado_servicio NOT NULL DEFAULT 'activo'
);

-- Antes era texto libre en abonos: "Transferencia", "transferencia" y
-- "Transf." partían el reporte por medio de pago en tres.
CREATE TABLE metodos_pago (
  id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      varchar(40)     NOT NULL UNIQUE,
  descripcion varchar(255),
  estado      estado_registro NOT NULL DEFAULT 'activo'
);

-- ================================================================ operación

-- La orden ya no cuelga del agendamiento ni guarda un único servicio:
--   · los servicios van en orden_servicio_detalle (una orden, varios);
--   · las visitas van en agendamientos, que apunta a la orden (una orden,
--     varias visitas: la reprogramada no borra la anterior).
-- El código visible (OS-0147) se arma con el id.
CREATE TABLE ordenes_servicio (
  id                   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id           int          NOT NULL REFERENCES clientes (id),
  -- Responsable de la orden. Nulo mientras no se asigna.
  tecnico_id           int          REFERENCES tecnicos (id),
  estado               estado_orden NOT NULL DEFAULT 'nueva',
  descripcion_problema text         NOT NULL,
  direccion_servicio   varchar(200) NOT NULL,
  fecha_ingreso        timestamptz  NOT NULL DEFAULT now(),
  fecha_entrega        timestamptz,
  CONSTRAINT ck_ordenes_fechas
    CHECK (fecha_entrega IS NULL OR fecha_entrega >= fecha_ingreso),
  CONSTRAINT ck_ordenes_entrega
    CHECK (estado <> 'completada' OR fecha_entrega IS NOT NULL)
);

-- El precio y la garantía se COPIAN del catálogo al crear la línea. Si mañana
-- sube el precio del servicio, las órdenes ya cerradas no cambian de valor.
CREATE TABLE orden_servicio_detalle (
  id              int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_id        int           NOT NULL REFERENCES ordenes_servicio (id) ON DELETE CASCADE,
  servicio_id     int           NOT NULL REFERENCES servicios (id),
  cantidad        int           NOT NULL DEFAULT 1 CHECK (cantidad > 0),
  precio_unitario numeric(10,2) NOT NULL CHECK (precio_unitario >= 0),
  dias_garantia   int           NOT NULL DEFAULT 0 CHECK (dias_garantia >= 0),
  subtotal        numeric(12,2) GENERATED ALWAYS AS (cantidad * precio_unitario) STORED,
  UNIQUE (orden_id, servicio_id)
);

-- Ya no repite cliente ni servicio: salen de la orden. Solo guarda lo que es
-- propio de la visita: quién va, cuándo y cómo quedó.
CREATE TABLE agendamientos (
  id               int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_id         int           NOT NULL REFERENCES ordenes_servicio (id) ON DELETE CASCADE,
  tecnico_id       int           NOT NULL REFERENCES tecnicos (id),
  fecha_programada timestamptz   NOT NULL,
  estado           estado_agenda NOT NULL DEFAULT 'programado',
  notas            text,
  fecha_creacion   timestamptz   NOT NULL DEFAULT now()
);

-- Una orden puede tener varios: uno por visita.
CREATE TABLE diagnosticos (
  id                 int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_id           int         NOT NULL REFERENCES ordenes_servicio (id) ON DELETE CASCADE,
  tecnico_id         int         NOT NULL REFERENCES tecnicos (id),
  hallazgos          text        NOT NULL,
  solucion_propuesta text,
  fecha_diagnostico  timestamptz NOT NULL DEFAULT now()
);

-- ==================================================================== venta

-- Una venta por orden. Sin cliente_id (sale de la orden) y sin
-- saldo_pendiente (se calcula en v_ventas: guardado se desincroniza con el
-- primer abono corregido).
CREATE TABLE ventas (
  id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_id    int           NOT NULL UNIQUE REFERENCES ordenes_servicio (id),
  monto_total numeric(12,2) NOT NULL CHECK (monto_total >= 0),
  estado      estado_venta  NOT NULL DEFAULT 'vigente',
  fecha_venta timestamptz   NOT NULL DEFAULT now()
);

CREATE TABLE abonos (
  id             int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venta_id       int           NOT NULL REFERENCES ventas (id) ON DELETE CASCADE,
  metodo_pago_id int           NOT NULL REFERENCES metodos_pago (id),
  -- Anticipo del 50 % o saldo, como lo describe la ficha.
  tipo_pago      tipo_pago     NOT NULL,
  monto          numeric(12,2) NOT NULL CHECK (monto > 0),
  estado         estado_abono  NOT NULL DEFAULT 'por_conciliar',
  referencia     varchar(100),
  fecha_abono    timestamptz   NOT NULL DEFAULT now()
);

-- ================================================================== índices
-- Sobre las columnas por las que el portal filtra, ordena y une.

CREATE INDEX ix_usuarios_rol          ON usuarios (rol_id);
CREATE INDEX ix_clientes_nombre       ON clientes (lower(nombre));
CREATE INDEX ix_servicios_categoria   ON servicios (categoria_id);
CREATE INDEX ix_ordenes_estado        ON ordenes_servicio (estado);
CREATE INDEX ix_ordenes_cliente       ON ordenes_servicio (cliente_id);
CREATE INDEX ix_ordenes_tecnico       ON ordenes_servicio (tecnico_id);
CREATE INDEX ix_ordenes_fecha_ingreso ON ordenes_servicio (fecha_ingreso DESC);
CREATE INDEX ix_detalle_servicio      ON orden_servicio_detalle (servicio_id);
CREATE INDEX ix_agenda_orden          ON agendamientos (orden_id);
CREATE INDEX ix_agenda_tecnico_fecha  ON agendamientos (tecnico_id, fecha_programada);
CREATE INDEX ix_diagnosticos_orden    ON diagnosticos (orden_id);
CREATE INDEX ix_abonos_venta          ON abonos (venta_id);
CREATE INDEX ix_abonos_metodo         ON abonos (metodo_pago_id);

-- ================================================================== reglas
-- Dos reglas que una llave foránea sola no puede expresar.

-- 1. La cuenta de un cliente o de un técnico tiene el rol que corresponde.
--    Una FK a usuarios no distingue roles: sin esto se podía colgar la ficha
--    de un técnico de la cuenta de un cliente.
--    Uso: exigir_rol('<columna>', '<rol>' [, '<otro rol>' ...])
CREATE FUNCTION exigir_rol() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
  usuario int  := (to_jsonb(NEW) ->> TG_ARGV[0])::int;
  rol     text;
BEGIN
  IF usuario IS NULL THEN
    RETURN NEW;
  END IF;

  SELECT r.nombre INTO rol
    FROM usuarios u JOIN roles r ON r.id = u.rol_id
   WHERE u.id = usuario;

  IF rol IS NULL OR NOT rol = ANY (TG_ARGV[1:]) THEN
    RAISE EXCEPTION '%.% = %: el usuario debe tener rol %, y tiene rol %',
      TG_TABLE_NAME, TG_ARGV[0], usuario,
      array_to_string(TG_ARGV[1:], ' o '), coalesce(rol, '(no existe)')
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NEW;
END $$;

CREATE TRIGGER tg_clientes_rol BEFORE INSERT OR UPDATE OF usuario_id
  ON clientes FOR EACH ROW EXECUTE FUNCTION exigir_rol('usuario_id', 'cliente');
CREATE TRIGGER tg_tecnicos_rol BEFORE INSERT OR UPDATE OF usuario_id
  ON tecnicos FOR EACH ROW EXECUTE FUNCTION exigir_rol('usuario_id', 'tecnico');

-- 2. Nadie abona más de lo que se debe, ni sobre una venta anulada.
--    Los reembolsados no cuentan como abonado.
CREATE FUNCTION validar_abono() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
  total   numeric;
  estado_ estado_venta;
  abonado numeric;
BEGIN
  IF NEW.estado = 'reembolsado' THEN
    RETURN NEW;
  END IF;

  -- FOR UPDATE: dos abonos simultáneos a la misma venta se atienden en fila.
  SELECT v.monto_total, v.estado INTO total, estado_
    FROM ventas v WHERE v.id = NEW.venta_id FOR UPDATE;

  IF estado_ = 'anulada' THEN
    RAISE EXCEPTION 'La venta % está anulada y no recibe abonos', NEW.venta_id
      USING ERRCODE = 'check_violation';
  END IF;

  SELECT coalesce(sum(a.monto), 0) INTO abonado
    FROM abonos a
   WHERE a.venta_id = NEW.venta_id
     AND a.estado <> 'reembolsado'
     AND a.id IS DISTINCT FROM NEW.id;

  IF abonado + NEW.monto > total THEN
    RAISE EXCEPTION 'El abono de % supera el saldo de la venta % (saldo: %)',
      NEW.monto, NEW.venta_id, total - abonado
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NEW;
END $$;

CREATE TRIGGER tg_abonos_saldo BEFORE INSERT OR UPDATE OF monto, estado, venta_id
  ON abonos FOR EACH ROW EXECUTE FUNCTION validar_abono();

-- ==================================================================== vista
-- Lo que antes se guardaba (saldo_pendiente, estado_pago) y ahora se calcula.
-- Se consulta igual que una tabla:  SELECT * FROM v_ventas WHERE saldo > 0;

CREATE VIEW v_ventas AS
SELECT
  v.id,
  v.orden_id,
  o.cliente_id,
  v.monto_total,
  coalesce(ab.abonado, 0)                         AS abonado,
  v.monto_total - coalesce(ab.abonado, 0)         AS saldo,
  CASE
    WHEN v.estado = 'anulada'                      THEN 'anulada'
    WHEN coalesce(ab.abonado, 0) >= v.monto_total  THEN 'pagado'
    WHEN coalesce(ab.abonado, 0) > 0               THEN 'parcial'
    ELSE                                                'pendiente'
  END                                             AS estado_pago,
  v.estado,
  v.fecha_venta
FROM ventas v
JOIN ordenes_servicio o ON o.id = v.orden_id
LEFT JOIN LATERAL (
  SELECT sum(a.monto) AS abonado
    FROM abonos a
   WHERE a.venta_id = v.id AND a.estado <> 'reembolsado'
) ab ON true;

COMMIT;
