-- ============================================================================
--  Portal RvR Tecnologías · Esquema PostgreSQL · Modelo v6
--
--  Base:     la imagen «BASE DE DATOS FINAL» (16 tablas, dbdiagram.io).
--  Ajustes:  los 11 que exige la hoja «Control de cambios v6» de la Matriz de
--            Historias de Usuario, y las columnas o tablas que piden los
--            criterios de aceptación y que el diagrama no tenía. Cada ajuste
--            está marcado en su tabla con [AJUSTE v6-n] o [CA_xx_yy].
--
--  Tablas del diagrama (mismos nombres y columnas):
--    rol · permiso · rol_x_permiso · usuario · cliente · servicio
--    cotizacion · detalle_cotizacion · diagnostico · orden · detalle_orden
--    ventas · abonos · tecnico (antes «terceros») · agendamiento · disponibilidad
--
--  Tablas nuevas que piden la ficha y la matriz v6:
--    registro_acceso   HU_74  auditoría de ingresos             [AJUSTE v6-8]
--    material_orden    Móvil HU_07  materiales utilizados       [AJUSTE v6-7]
--    historial_orden   Móvil HU_10  historial de cambios de estado
--    notificacion      CA_78_04, CA_80_03, CA_81_03, Móvil CA_04_03
--
--  Los estados son varchar(20) como en el diagrama, pero con CHECK: la base
--  ya no acepta «finalizada», «Finalizada» y «finalzada» como tres valores.
--
--  ⚠ Empieza con DROP: solo se corre sobre una base sin datos reales.
--  Ejecutar con:  psql -U postgres -d rvr -f db/01-esquema.sql
-- ============================================================================

BEGIN;

-- ------------------------------------------------------------------ limpieza
-- Nombres de este modelo y del anterior (15 tablas), para migrar desde él.
DROP VIEW  IF EXISTS v_ventas CASCADE;
DROP TABLE IF EXISTS
  notificacion, historial_orden, material_orden, registro_acceso,
  abonos, ventas, agendamiento, disponibilidad, detalle_orden, diagnostico,
  detalle_cotizacion, cotizacion, orden, servicio, tecnico, terceros, cliente,
  usuario, rol_x_permiso, permiso, rol,
  -- modelo anterior
  diagnosticos, agendamientos, orden_servicio_detalle, ordenes_servicio,
  metodos_pago, servicios, categorias, tecnicos, clientes, usuarios,
  roles_permisos, permisos, roles
CASCADE;
DROP FUNCTION IF EXISTS exigir_rol, validar_abono, fn_monto_cotizacion,
  fn_codigo_orden, fn_detalle_orden_mismo_cliente, fn_abono_venta,
  fn_franja_sin_cruce, fn_historial_orden, fn_solo_lectura CASCADE;
DROP TYPE IF EXISTS estado_registro, estado_usuario, estado_servicio,
  estado_orden, estado_agenda, estado_venta, tipo_pago, estado_abono,
  estado_tecnico, tipo_documento CASCADE;

-- ============================================================== CONFIGURACIÓN

-- HU_01–HU_06 · Gestión de Roles
CREATE TABLE rol (
  id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      varchar(50)  NOT NULL,
  descripcion varchar(255),
  estado      varchar(20)  NOT NULL DEFAULT 'activo',
  CONSTRAINT uq_rol_nombre UNIQUE (nombre),                      -- CA_01_02
  CONSTRAINT ck_rol_estado CHECK (estado IN ('activo', 'inactivo'))
);

-- HU_66–HU_71 · Gestión de Permisos
CREATE TABLE permiso (
  id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      varchar(50)  NOT NULL,
  modulo      varchar(50)  NOT NULL,
  descripcion varchar(255),
  estado      varchar(20)  NOT NULL DEFAULT 'activo',
  CONSTRAINT uq_permiso_nombre_modulo UNIQUE (nombre, modulo),   -- CA_66_02
  CONSTRAINT ck_permiso_estado CHECK (estado IN ('activo', 'inactivo'))
);

CREATE TABLE rol_x_permiso (
  rol_id     int NOT NULL REFERENCES rol (id)     ON DELETE CASCADE,
  permiso_id int NOT NULL REFERENCES permiso (id) ON DELETE RESTRICT,
  PRIMARY KEY (rol_id, permiso_id)
);
CREATE INDEX ix_rol_x_permiso_permiso ON rol_x_permiso (permiso_id);

-- ================================================================== USUARIOS

-- HU_07–HU_14, HU_72–HU_73
CREATE TABLE usuario (
  id                 int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rol_id             int          NOT NULL REFERENCES rol (id),
  nombre_usuario     varchar(50)  NOT NULL,
  correo             varchar(100) NOT NULL,
  contrasena_hash    varchar(255) NOT NULL,                      -- CA_07_03 bcrypt
  nombres            varchar(100) NOT NULL,
  apellidos          varchar(100) NOT NULL,
  telefono           varchar(20),
  estado             varchar(20)  NOT NULL DEFAULT 'activo',
  -- [AJUSTE v6-9] Recuperación de contraseña (HU_72, HU_73). Se guarda el
  -- SHA-256 del token, nunca el token: quien lea la tabla no puede usarlo.
  token_recuperacion varchar(255),
  token_vence        timestamp,
  -- [CA_73_05, Móvil CA_02_02] Al restablecer la contraseña o cerrar sesión
  -- se incrementa: todos los tokens firmados con la versión anterior mueren.
  version_sesion     int          NOT NULL DEFAULT 0,
  CONSTRAINT uq_usuario_nombre_usuario UNIQUE (nombre_usuario),  -- CA_07_02
  CONSTRAINT uq_usuario_correo         UNIQUE (correo),
  CONSTRAINT ck_usuario_estado CHECK (estado IN ('activo', 'inactivo')),
  CONSTRAINT ck_usuario_correo CHECK (correo = lower(correo))
);
CREATE INDEX ix_usuario_rol ON usuario (rol_id);

-- [AJUSTE v6-8] HU_74 · Registro de accesos (solo lectura: CA_74_04)
CREATE TABLE registro_acceso (
  id            int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id    int          REFERENCES usuario (id),
  identificador varchar(100) NOT NULL,       -- lo que se digitó: correo o usuario
  resultado     varchar(20)  NOT NULL,
  canal         varchar(10)  NOT NULL DEFAULT 'web',
  ip            varchar(45),
  fecha         timestamp    NOT NULL DEFAULT now(),
  CONSTRAINT ck_acceso_resultado CHECK (resultado IN
    ('exitoso', 'fallido', 'bloqueado', 'cierre_sesion', 'recuperacion', 'restablecimiento')),
  CONSTRAINT ck_acceso_canal CHECK (canal IN ('web', 'movil'))
);
CREATE INDEX ix_acceso_fecha ON registro_acceso (fecha DESC);
CREATE INDEX ix_acceso_identificador ON registro_acceso (lower(identificador), fecha DESC);

-- ================================================================== PERSONAS

-- HU_31–HU_35, HU_83, HU_75–HU_77
CREATE TABLE cliente (
  id                  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  documento_identidad varchar(20)  NOT NULL,
  nombres             varchar(100) NOT NULL,
  apellidos           varchar(100) NOT NULL,
  telefono            varchar(20),
  direccion           varchar(150),
  correo              varchar(100),
  fecha_registro      timestamp    NOT NULL DEFAULT now(),        -- CA_31_04
  -- [AJUSTE v6-1] Cuenta del portal (HU_75). Nula si lo registró el admin.
  usuario_id          int          REFERENCES usuario (id),
  -- [AJUSTE v6-11] HU_83 · activo / inactivo
  estado              varchar(20)  NOT NULL DEFAULT 'activo',
  CONSTRAINT uq_cliente_documento UNIQUE (documento_identidad),  -- CA_31_02
  CONSTRAINT uq_cliente_usuario   UNIQUE (usuario_id),
  CONSTRAINT ck_cliente_estado CHECK (estado IN ('activo', 'inactivo'))
);

-- [AJUSTE v6-10] «terceros» pasa a llamarse «tecnico» (HU_22–HU_27)
CREATE TABLE tecnico (
  id                  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  documento_identidad varchar(20)  NOT NULL,
  nombres             varchar(100) NOT NULL,
  apellidos           varchar(100) NOT NULL,
  especialidad        varchar(100),
  telefono            varchar(20),
  correo              varchar(100),
  estado              varchar(20)  NOT NULL DEFAULT 'activo',
  -- Cuenta para la aplicación móvil (Móvil HU_01). Nula si no la tiene.
  usuario_id          int          REFERENCES usuario (id),
  CONSTRAINT uq_tecnico_documento UNIQUE (documento_identidad),  -- CA_22_02
  CONSTRAINT uq_tecnico_usuario   UNIQUE (usuario_id),
  CONSTRAINT ck_tecnico_estado CHECK (estado IN ('activo', 'inactivo'))
);

-- HU_28–HU_30 · Gestión de Horarios Técnicos
CREATE TABLE disponibilidad (
  id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tecnico_id  int         NOT NULL REFERENCES tecnico (id),
  fecha       date        NOT NULL,
  hora_inicio time        NOT NULL,
  hora_fin    time        NOT NULL,
  estado      varchar(20) NOT NULL DEFAULT 'disponible',          -- CA_28_04
  motivo      varchar(255),            -- incapacidad, permiso… (novedad de la ficha)
  CONSTRAINT ck_franja_horas  CHECK (hora_fin > hora_inicio),     -- CA_28_02
  CONSTRAINT ck_franja_estado CHECK (estado IN ('disponible', 'ocupada', 'bloqueada'))
);
CREATE INDEX ix_disponibilidad_tecnico_fecha ON disponibilidad (tecnico_id, fecha);

-- ================================================================= SERVICIOS

-- HU_15–HU_21
CREATE TABLE servicio (
  id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      varchar(100)  NOT NULL,
  descripcion text,
  precio_base decimal(10,2) NOT NULL,
  estado      varchar(20)   NOT NULL DEFAULT 'activo',
  -- [AJUSTE v6-3] Categoría, del listado definido para el catálogo (CA_15_03)
  categoria   varchar(50)   NOT NULL,
  CONSTRAINT uq_servicio_nombre UNIQUE (nombre),                  -- CA_15_02
  CONSTRAINT ck_servicio_precio CHECK (precio_base > 0),          -- CA_15_04
  CONSTRAINT ck_servicio_estado CHECK (estado IN ('activo', 'inactivo')),
  CONSTRAINT ck_servicio_categoria CHECK (categoria IN
    ('Mantenimiento', 'Servidores', 'Redes', 'Cámaras de seguridad', 'Alarmas'))
);

-- ================================================================ OPERACIÓN

-- HU_44–HU_50, HU_82
CREATE TABLE orden (
  id             int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_orden   varchar(50) NOT NULL,
  fecha_creacion timestamp   NOT NULL DEFAULT now(),
  estado         varchar(20) NOT NULL DEFAULT 'esperando_anticipo', -- CA_44_06
  observaciones  text,
  CONSTRAINT uq_orden_codigo UNIQUE (codigo_orden),               -- CA_44_02
  CONSTRAINT ck_orden_estado CHECK (estado IN
    ('esperando_anticipo', 'en_proceso', 'en_espera_repuesto', 'finalizada', 'cancelada'))
);

-- HU_36–HU_41, HU_78–HU_81, Móvil HU_11
CREATE TABLE cotizacion (
  id               int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id       int           NOT NULL REFERENCES cliente (id),
  fecha_cotizacion timestamp     NOT NULL DEFAULT now(),
  monto_total      decimal(10,2) NOT NULL DEFAULT 0,  -- lo calcula la base (CA_36_04)
  estado           varchar(20)   NOT NULL DEFAULT 'solicitada',
  -- [AJUSTE v6-5] Envío y respuesta del cliente
  fecha_envio      timestamp,                                       -- CA_81_02
  fecha_respuesta  timestamp,                                       -- CA_41_03
  motivo_rechazo   varchar(255),                                    -- CA_80_04
  -- [CA_38_02] Quién la originó: la solicitud del cliente, el admin o el técnico
  origen           varchar(20)   NOT NULL DEFAULT 'administrador',
  -- [CA_78_02] Problema y dirección que describe el cliente al solicitar
  descripcion      text,
  direccion        varchar(150),
  -- [Móvil CA_11_02] Recotización por repuesto: la orden de la que nace
  orden_id         int           REFERENCES orden (id),
  -- [CA_40_05] Quién registró la decisión (admin por teléfono o el cliente)
  respondida_por   int           REFERENCES usuario (id),
  CONSTRAINT ck_cotizacion_estado CHECK (estado IN
    ('solicitada', 'pendiente', 'aprobada', 'rechazada')),
  CONSTRAINT ck_cotizacion_origen CHECK (origen IN ('cliente', 'administrador', 'tecnico')),
  CONSTRAINT ck_cotizacion_monto  CHECK (monto_total >= 0)
);
CREATE INDEX ix_cotizacion_cliente ON cotizacion (cliente_id);
CREATE INDEX ix_cotizacion_estado  ON cotizacion (estado, fecha_cotizacion DESC);

CREATE TABLE detalle_cotizacion (
  id              int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cotizacion_id   int           NOT NULL REFERENCES cotizacion (id) ON DELETE CASCADE,
  -- Nulo en los repuestos: no están en el catálogo de servicios
  servicio_id     int           REFERENCES servicio (id),
  cantidad        int           NOT NULL,
  precio_unitario decimal(10,2) NOT NULL,       -- congelado al cotizar (CA_18_03)
  -- Calculado por la base: nunca contradice cantidad × precio (CA_36_04)
  subtotal        decimal(10,2) GENERATED ALWAYS AS (cantidad * precio_unitario) STORED,
  -- [AJUSTE v6-4] Servicio del catálogo o repuesto/insumo con descripción libre
  tipo_item       varchar(20)   NOT NULL DEFAULT 'servicio',
  descripcion     varchar(255),
  CONSTRAINT ck_detalle_cot_cantidad CHECK (cantidad > 0),
  CONSTRAINT ck_detalle_cot_precio   CHECK (precio_unitario >= 0),
  CONSTRAINT ck_detalle_cot_tipo     CHECK (tipo_item IN ('servicio', 'repuesto')),
  CONSTRAINT ck_detalle_cot_item CHECK (
    (tipo_item = 'servicio' AND servicio_id IS NOT NULL) OR
    (tipo_item = 'repuesto' AND descripcion IS NOT NULL))
);
CREATE INDEX ix_detalle_cot_cotizacion ON detalle_cotizacion (cotizacion_id);
CREATE INDEX ix_detalle_cot_servicio   ON detalle_cotizacion (servicio_id);

-- [AJUSTE v6-6] Cada ítem de la orden viene de un ítem de cotización aprobada
CREATE TABLE detalle_orden (
  id                    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_id              int         NOT NULL REFERENCES orden (id),
  detalle_cotizacion_id int         NOT NULL REFERENCES detalle_cotizacion (id),
  fecha_asignacion      timestamp   NOT NULL DEFAULT now(),         -- CA_44_05
  estado_item           varchar(20) NOT NULL DEFAULT 'pendiente',
  notas_tecnico         text,                                       -- CA_47_02
  -- Un ítem de cotización genera un solo ítem de orden (CA_44_04)
  CONSTRAINT uq_detalle_orden_item UNIQUE (detalle_cotizacion_id),
  CONSTRAINT ck_detalle_orden_estado CHECK (estado_item IN ('pendiente', 'en_proceso', 'completado'))
);
CREATE INDEX ix_detalle_orden_orden ON detalle_orden (orden_id);

-- [AJUSTE v6-7] El diagnóstico cuelga de la orden: lo registra el técnico
-- desde el móvil (Móvil HU_06 y HU_08) y el admin lo ve en HU_50.
CREATE TABLE diagnostico (
  id                int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_id          int       NOT NULL REFERENCES orden (id),
  tecnico_id        int       REFERENCES tecnico (id),
  hallazgos         text      NOT NULL,
  solucion_aplicada text,
  fecha_diagnostico timestamp NOT NULL DEFAULT now(),
  fecha_solucion    timestamp,
  CONSTRAINT uq_diagnostico_orden UNIQUE (orden_id)
);

-- [AJUSTE v6-7] Móvil HU_07 · Materiales utilizados (varios por orden)
CREATE TABLE material_orden (
  id             int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_id       int          NOT NULL REFERENCES orden (id),
  tecnico_id     int          REFERENCES tecnico (id),
  descripcion    varchar(150) NOT NULL,
  cantidad       int          NOT NULL,
  fecha_registro timestamp    NOT NULL DEFAULT now(),
  CONSTRAINT ck_material_cantidad CHECK (cantidad > 0)
);
CREATE INDEX ix_material_orden ON material_orden (orden_id);

-- Móvil HU_10 · Historial de cambios de estado y observaciones de la orden
CREATE TABLE historial_orden (
  id              int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_id        int          NOT NULL REFERENCES orden (id),
  estado_anterior varchar(20),
  estado_nuevo    varchar(20),
  descripcion     varchar(255) NOT NULL,
  usuario_id      int          REFERENCES usuario (id),
  fecha           timestamp    NOT NULL DEFAULT now()
);
CREATE INDEX ix_historial_orden ON historial_orden (orden_id, fecha);

-- HU_51–HU_54
CREATE TABLE agendamiento (
  id                int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_id          int         NOT NULL REFERENCES orden (id),
  tecnico_id        int         NOT NULL REFERENCES tecnico (id),
  fecha_programada  timestamp   NOT NULL,
  estado            varchar(20) NOT NULL DEFAULT 'pendiente',
  notas             text,                                           -- CA_54_03
  -- Franja que ocupa: se libera al cancelar o reprogramar (CA_53_03, CA_54_02)
  disponibilidad_id int         REFERENCES disponibilidad (id),
  -- Móvil HU_04 / HU_05 · hora real de inicio y fin de la visita
  fecha_inicio      timestamp,
  fecha_fin         timestamp,
  CONSTRAINT ck_agenda_estado CHECK (estado IN
    ('pendiente', 'cumplida', 'reprogramada', 'cancelada')),
  CONSTRAINT ck_agenda_fin CHECK (fecha_fin IS NULL OR fecha_inicio IS NULL OR fecha_fin >= fecha_inicio)
);
CREATE INDEX ix_agenda_tecnico_fecha ON agendamiento (tecnico_id, fecha_programada);
CREATE INDEX ix_agenda_orden ON agendamiento (orden_id);
-- CA_51_03: un técnico no puede tener dos visitas activas a la misma hora
CREATE UNIQUE INDEX uq_agenda_tecnico_hora ON agendamiento (tecnico_id, fecha_programada)
  WHERE estado = 'pendiente';

-- ===================================================================== VENTA

-- HU_55–HU_57
CREATE TABLE ventas (
  id              int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_id        int           NOT NULL REFERENCES orden (id),
  monto_total     decimal(10,2) NOT NULL,
  monto_anticipo  decimal(10,2) NOT NULL,
  -- Lo mantiene la base con cada abono (fn_abono_venta); la API además lo
  -- recalcula al consultar (CA_56_02), así nunca se desincroniza.
  saldo_pendiente decimal(10,2) NOT NULL,
  estado_pago     varchar(20)   NOT NULL DEFAULT 'pendiente_anticipo', -- CA_55_04
  fecha_venta     timestamp     NOT NULL DEFAULT now(),
  CONSTRAINT uq_ventas_orden UNIQUE (orden_id),                    -- CA_55_02
  CONSTRAINT ck_ventas_total    CHECK (monto_total > 0),
  CONSTRAINT ck_ventas_anticipo CHECK (monto_anticipo >= 0 AND monto_anticipo <= monto_total),
  CONSTRAINT ck_ventas_saldo    CHECK (saldo_pendiente >= 0),
  CONSTRAINT ck_ventas_estado   CHECK (estado_pago IN
    ('pendiente_anticipo', 'abonada', 'pagada', 'anulada'))
);

-- HU_58–HU_59
CREATE TABLE abonos (
  id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venta_id    int           NOT NULL REFERENCES ventas (id),
  monto       decimal(10,2) NOT NULL,
  tipo_abono  varchar(20)   NOT NULL,
  metodo_pago varchar(50)   NOT NULL,
  referencia  varchar(100),
  fecha_abono timestamp     NOT NULL DEFAULT now(),                -- CA_58_03
  CONSTRAINT ck_abono_monto  CHECK (monto > 0),                     -- CA_58_02
  CONSTRAINT ck_abono_tipo   CHECK (tipo_abono IN ('anticipo', 'saldo')),
  -- Lista cerrada: con texto libre el reporte por medio de pago salía partido
  CONSTRAINT ck_abono_metodo CHECK (metodo_pago IN
    ('Efectivo', 'Transferencia', 'Nequi', 'Daviplata', 'Tarjeta'))
);
CREATE INDEX ix_abonos_venta ON abonos (venta_id);
CREATE INDEX ix_abonos_fecha ON abonos (fecha_abono DESC);

-- ============================================================= NOTIFICACIONES

CREATE TABLE notificacion (
  id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id int          NOT NULL REFERENCES usuario (id),
  titulo     varchar(120) NOT NULL,
  mensaje    varchar(255) NOT NULL,
  enlace     varchar(200),
  leida      boolean      NOT NULL DEFAULT false,
  fecha      timestamp    NOT NULL DEFAULT now()
);
CREATE INDEX ix_notificacion_usuario ON notificacion (usuario_id, leida, fecha DESC);

-- ================================================================== REGLAS

-- CA_36_04 / CA_39_03 · El monto total de la cotización es la suma de su detalle
CREATE FUNCTION fn_monto_cotizacion() RETURNS trigger AS $$
DECLARE
  cot int := coalesce(NEW.cotizacion_id, OLD.cotizacion_id);
BEGIN
  UPDATE cotizacion
     SET monto_total = coalesce((SELECT sum(subtotal) FROM detalle_cotizacion
                                  WHERE cotizacion_id = cot), 0)
   WHERE id = cot;
  IF TG_OP = 'UPDATE' AND OLD.cotizacion_id <> NEW.cotizacion_id THEN
    UPDATE cotizacion
       SET monto_total = coalesce((SELECT sum(subtotal) FROM detalle_cotizacion
                                    WHERE cotizacion_id = OLD.cotizacion_id), 0)
     WHERE id = OLD.cotizacion_id;
  END IF;
  RETURN NULL;
END $$ LANGUAGE plpgsql;

CREATE TRIGGER tg_monto_cotizacion
  AFTER INSERT OR UPDATE OR DELETE ON detalle_cotizacion
  FOR EACH ROW EXECUTE FUNCTION fn_monto_cotizacion();

-- CA_44_02 · Código de orden único e irrepetible: OS-2026-0001
CREATE FUNCTION fn_codigo_orden() RETURNS trigger AS $$
BEGIN
  IF NEW.codigo_orden IS NULL OR NEW.codigo_orden = '' THEN
    NEW.codigo_orden := 'OS-' || to_char(NEW.fecha_creacion, 'YYYY') || '-' ||
                        lpad(NEW.id::text, 4, '0');
  END IF;
  RETURN NEW;
END $$ LANGUAGE plpgsql;

CREATE TRIGGER tg_codigo_orden
  BEFORE INSERT ON orden
  FOR EACH ROW EXECUTE FUNCTION fn_codigo_orden();

-- Observación de la matriz v5: «nada impide que una orden mezcle diagnósticos
-- de dos clientes». Ahora la base lo impide, y solo acepta ítems aprobados.
CREATE FUNCTION fn_detalle_orden_mismo_cliente() RETURNS trigger AS $$
DECLARE
  cliente_nuevo int;
  estado_cot    varchar(20);
  otro_cliente  int;
BEGIN
  SELECT c.cliente_id, c.estado INTO cliente_nuevo, estado_cot
    FROM detalle_cotizacion dc JOIN cotizacion c ON c.id = dc.cotizacion_id
   WHERE dc.id = NEW.detalle_cotizacion_id;

  IF estado_cot <> 'aprobada' THEN
    RAISE EXCEPTION 'Solo los ítems de una cotización aprobada pueden pasar a una orden'
      USING ERRCODE = 'check_violation', CONSTRAINT = 'ck_detalle_orden_aprobada';
  END IF;

  SELECT c.cliente_id INTO otro_cliente
    FROM detalle_orden d
    JOIN detalle_cotizacion dc ON dc.id = d.detalle_cotizacion_id
    JOIN cotizacion c          ON c.id = dc.cotizacion_id
   WHERE d.orden_id = NEW.orden_id AND d.id <> coalesce(NEW.id, -1)
   LIMIT 1;

  IF otro_cliente IS NOT NULL AND otro_cliente <> cliente_nuevo THEN
    RAISE EXCEPTION 'Una orden no puede mezclar ítems de dos clientes'
      USING ERRCODE = 'check_violation', CONSTRAINT = 'ck_detalle_orden_cliente';
  END IF;
  RETURN NEW;
END $$ LANGUAGE plpgsql;

CREATE TRIGGER tg_detalle_orden_cliente
  BEFORE INSERT OR UPDATE OF detalle_cotizacion_id, orden_id ON detalle_orden
  FOR EACH ROW EXECUTE FUNCTION fn_detalle_orden_mismo_cliente();

-- CA_58_02 / CA_58_04 / CA_57_01 / CA_57_02 / CA_57_04
-- Valida el abono y deja la venta al día: saldo y estado de pago.
CREATE FUNCTION fn_abono_venta() RETURNS trigger AS $$
DECLARE
  v ventas%ROWTYPE;
  abonado numeric;
BEGIN
  SELECT * INTO v FROM ventas WHERE id = NEW.venta_id FOR UPDATE;
  IF v.estado_pago = 'anulada' THEN
    RAISE EXCEPTION 'La venta está anulada: no recibe abonos'
      USING ERRCODE = 'check_violation', CONSTRAINT = 'ck_abono_venta_anulada';
  END IF;

  SELECT coalesce(sum(monto), 0) INTO abonado FROM abonos WHERE venta_id = v.id;
  IF abonado + NEW.monto > v.monto_total THEN
    RAISE EXCEPTION 'El abono supera el saldo pendiente de la venta'
      USING ERRCODE = 'check_violation', CONSTRAINT = 'ck_abono_saldo';
  END IF;

  UPDATE ventas
     SET saldo_pendiente = monto_total - (abonado + NEW.monto),
         estado_pago = CASE
           WHEN monto_total - (abonado + NEW.monto) = 0 THEN 'pagada'
           WHEN abonado + NEW.monto >= monto_anticipo   THEN 'abonada'
           ELSE 'pendiente_anticipo' END
   WHERE id = v.id;
  RETURN NEW;
END $$ LANGUAGE plpgsql;

CREATE TRIGGER tg_abono_venta
  BEFORE INSERT ON abonos
  FOR EACH ROW EXECUTE FUNCTION fn_abono_venta();

-- CA_28_03 · Una franja no se cruza con otra del mismo técnico en la misma fecha
CREATE FUNCTION fn_franja_sin_cruce() RETURNS trigger AS $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM disponibilidad
     WHERE tecnico_id = NEW.tecnico_id AND fecha = NEW.fecha
       AND id <> coalesce(NEW.id, -1)
       AND NEW.hora_inicio < hora_fin AND hora_inicio < NEW.hora_fin
  ) THEN
    RAISE EXCEPTION 'La franja se cruza con otra del mismo técnico en esa fecha'
      USING ERRCODE = 'exclusion_violation', CONSTRAINT = 'ck_franja_cruce';
  END IF;
  RETURN NEW;
END $$ LANGUAGE plpgsql;

CREATE TRIGGER tg_franja_sin_cruce
  BEFORE INSERT OR UPDATE OF tecnico_id, fecha, hora_inicio, hora_fin ON disponibilidad
  FOR EACH ROW EXECUTE FUNCTION fn_franja_sin_cruce();

-- Móvil HU_10 · Cada cambio de estado de la orden queda en su historial.
-- Quién lo hizo llega en la variable de sesión rvr.usuario_id (la pone la API).
CREATE FUNCTION fn_historial_orden() RETURNS trigger AS $$
DECLARE
  quien int := nullif(current_setting('rvr.usuario_id', true), '')::int;
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO historial_orden (orden_id, estado_anterior, estado_nuevo, descripcion, usuario_id, fecha)
    VALUES (NEW.id, NULL, NEW.estado, 'Orden creada', quien, NEW.fecha_creacion);
  ELSIF NEW.estado IS DISTINCT FROM OLD.estado THEN
    INSERT INTO historial_orden (orden_id, estado_anterior, estado_nuevo, descripcion, usuario_id)
    VALUES (NEW.id, OLD.estado, NEW.estado,
            coalesce(nullif(current_setting('rvr.motivo', true), ''), 'Cambio de estado'), quien);
  END IF;
  RETURN NULL;
END $$ LANGUAGE plpgsql;

CREATE TRIGGER tg_historial_orden
  AFTER INSERT OR UPDATE OF estado ON orden
  FOR EACH ROW EXECUTE FUNCTION fn_historial_orden();

-- CA_74_04 · El registro de accesos y el historial no se modifican ni se borran
CREATE FUNCTION fn_solo_lectura() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'La tabla % es de solo lectura', TG_TABLE_NAME
    USING ERRCODE = 'insufficient_privilege';
END $$ LANGUAGE plpgsql;

CREATE TRIGGER tg_acceso_solo_lectura
  BEFORE UPDATE OR DELETE ON registro_acceso
  FOR EACH ROW EXECUTE FUNCTION fn_solo_lectura();

CREATE TRIGGER tg_historial_solo_lectura
  BEFORE UPDATE OR DELETE ON historial_orden
  FOR EACH ROW EXECUTE FUNCTION fn_solo_lectura();

-- ================================================================== VISTAS

-- CA_56_01 / CA_56_02 · Estado de cuenta calculado de cada venta, con su
-- cliente (orden → detalle_orden → detalle_cotizacion → cotizacion → cliente).
CREATE VIEW v_ventas AS
SELECT v.id, v.orden_id, v.monto_total, v.monto_anticipo, v.estado_pago, v.fecha_venta,
       coalesce(a.abonado, 0)                     AS abonado,
       v.monto_total - coalesce(a.abonado, 0)     AS saldo,
       cli.cliente_id
  FROM ventas v
  LEFT JOIN (SELECT venta_id, sum(monto) AS abonado FROM abonos GROUP BY venta_id) a
         ON a.venta_id = v.id
  LEFT JOIN LATERAL (
    SELECT c.cliente_id
      FROM detalle_orden d
      JOIN detalle_cotizacion dc ON dc.id = d.detalle_cotizacion_id
      JOIN cotizacion c          ON c.id = dc.cotizacion_id
     WHERE d.orden_id = v.orden_id
     LIMIT 1
  ) cli ON true;

-- La orden con su cliente y su cotización de origen: la usan casi todas las
-- consultas, así el camino de cuatro tablas se escribe una sola vez.
CREATE VIEW v_orden_cliente AS
SELECT o.id AS orden_id, x.cliente_id, x.cotizacion_id
  FROM orden o
  LEFT JOIN LATERAL (
    SELECT c.cliente_id, c.id AS cotizacion_id
      FROM detalle_orden d
      JOIN detalle_cotizacion dc ON dc.id = d.detalle_cotizacion_id
      JOIN cotizacion c          ON c.id = dc.cotizacion_id
     WHERE d.orden_id = o.id
     ORDER BY c.fecha_cotizacion
     LIMIT 1
  ) x ON true;

COMMIT;
