import { lazy } from 'react'

/*
 * Cada módulo se descarga la primera vez que se abre: el cliente nunca baja el
 * código del portal administrativo, ni el personal el del portal del cliente.
 */
export const LandingPage = lazy(() => import('@features/landing').then((m) => ({ default: m.LandingPage })))
export const AgendaPage = lazy(() => import('@features/agenda').then((m) => ({ default: m.AgendaPage })))
export const ClienteDetallePage = lazy(() => import('@features/clientes').then((m) => ({ default: m.ClienteDetallePage })))
export const ClientesPage = lazy(() => import('@features/clientes').then((m) => ({ default: m.ClientesPage })))
export const CotizacionDetallePage = lazy(() => import('@features/cotizaciones').then((m) => ({ default: m.CotizacionDetallePage })))
export const CotizacionesPage = lazy(() => import('@features/cotizaciones').then((m) => ({ default: m.CotizacionesPage })))
export const CotizacionFormPage = lazy(() => import('@features/cotizaciones').then((m) => ({ default: m.CotizacionFormPage })))
export const HorariosPage = lazy(() => import('@features/horarios').then((m) => ({ default: m.HorariosPage })))
export const NuevaOrdenPage = lazy(() => import('@features/ordenes').then((m) => ({ default: m.NuevaOrdenPage })))
export const OrdenDetallePage = lazy(() => import('@features/ordenes').then((m) => ({ default: m.OrdenDetallePage })))
export const OrdenesPage = lazy(() => import('@features/ordenes').then((m) => ({ default: m.OrdenesPage })))
export const PerfilPage = lazy(() => import('@features/perfil').then((m) => ({ default: m.PerfilPage })))
export const PermisoDetallePage = lazy(() => import('@features/permisos').then((m) => ({ default: m.PermisoDetallePage })))
export const PermisosPage = lazy(() => import('@features/permisos').then((m) => ({ default: m.PermisosPage })))
export const CatalogoPublicoPage = lazy(() => import('@features/portal').then((m) => ({ default: m.CatalogoPublicoPage })))
export const MiCotizacionPage = lazy(() => import('@features/portal').then((m) => ({ default: m.MiCotizacionPage })))
export const MiOrdenPage = lazy(() => import('@features/portal').then((m) => ({ default: m.MiOrdenPage })))
export const MiPerfilPage = lazy(() => import('@features/portal').then((m) => ({ default: m.MiPerfilPage })))
export const MisCotizacionesPage = lazy(() => import('@features/portal').then((m) => ({ default: m.MisCotizacionesPage })))
export const MisOrdenesPage = lazy(() => import('@features/portal').then((m) => ({ default: m.MisOrdenesPage })))
export const PortalCatalogoPage = lazy(() => import('@features/portal').then((m) => ({ default: m.PortalCatalogoPage })))
export const PortalInicioPage = lazy(() => import('@features/portal').then((m) => ({ default: m.PortalInicioPage })))
export const SolicitarPage = lazy(() => import('@features/portal').then((m) => ({ default: m.SolicitarPage })))
export const RolDetallePage = lazy(() => import('@features/roles').then((m) => ({ default: m.RolDetallePage })))
export const RolesPage = lazy(() => import('@features/roles').then((m) => ({ default: m.RolesPage })))
export const RolFormPage = lazy(() => import('@features/roles').then((m) => ({ default: m.RolFormPage })))
export const ServicioDetallePage = lazy(() => import('@features/servicios').then((m) => ({ default: m.ServicioDetallePage })))
export const ServiciosPage = lazy(() => import('@features/servicios').then((m) => ({ default: m.ServiciosPage })))
export const EstadisticasPage = lazy(() => import('@features/tablero').then((m) => ({ default: m.EstadisticasPage })))
export const IndicadoresPage = lazy(() => import('@features/tablero').then((m) => ({ default: m.IndicadoresPage })))
export const ReportesPage = lazy(() => import('@features/tablero').then((m) => ({ default: m.ReportesPage })))
export const TecnicoDetallePage = lazy(() => import('@features/tecnicos').then((m) => ({ default: m.TecnicoDetallePage })))
export const TecnicosPage = lazy(() => import('@features/tecnicos').then((m) => ({ default: m.TecnicosPage })))
export const AccesosPage = lazy(() => import('@features/usuarios').then((m) => ({ default: m.AccesosPage })))
export const UsuarioDetallePage = lazy(() => import('@features/usuarios').then((m) => ({ default: m.UsuarioDetallePage })))
export const UsuariosPage = lazy(() => import('@features/usuarios').then((m) => ({ default: m.UsuariosPage })))
export const AbonosPage = lazy(() => import('@features/ventas').then((m) => ({ default: m.AbonosPage })))
export const VentaDetallePage = lazy(() => import('@features/ventas').then((m) => ({ default: m.VentaDetallePage })))
export const VentasPage = lazy(() => import('@features/ventas').then((m) => ({ default: m.VentasPage })))
